- name: Setup Machine
  hosts: localhost
  # become: yes # Use sudo to gain root privileges
  become_method: sudo
  tasks:
    - include: tasks/brew-setup.yml
    - include: tasks/cargo-setup.yml
    - include: tasks/ssh_setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/gpg_setup.yml
    - include: tasks/pass-setup.yml
    - include: tasks/dotfiles-setup.yml
# Add any other tasks as needed
