- name: Verify Stow installation
  become: no
  command: stow --version
  register: stow_version
  changed_when: false
  failed_when: false
  tags:
    - verify
    - dotfiles
    - stow

- name: Cloning dotfiles
  become: no
  ansible.builtin.git:
    repo: "git@github.com:{{git_account}}/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Delete possible zshenv file
  become: no
  shell: rm $HOME/.zshenv || true
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  become: no
  shell: cd $HOME/dotfiles && stow --target=$HOME */
  tags:
    - install
    - dotfiles
    - stow
