- name: Verify Brew installation
  shell: which brew
  register: brew_exists
  ignore_errors: true
  failed_when: brew_exists.rc != 1 and brew_exists.rc != 0

- name: Install Brew
  become: no
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: brew_exists.rc == 1

- name: Update Brew
  become: no
  homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Verify Brewfile exists in dotfiles repo
  become: no
  stat:
    path: "{{ lookup('env', 'HOME') }}/dotfiles/Brewfile"
  register: brewfile

- name: Install Brew packages from dotfiles Brewfile
  become: no
  command:
    argv:
      - brew
      - bundle
      - --file={{ lookup('env', 'HOME') }}/dotfiles/Brewfile
  when: brewfile.stat.exists
